verifyDepsBeforeRun: false
strictPeerDependencies: false
shamefullyHoist: true
onlyBuiltDependencies:
  - esbuild
  - workerd
  - '@cloudflare/workerd-darwin-64'
  - '@cloudflare/workerd-darwin-arm64'
  - better-sqlite3
